version: '3.7'

networks:
  app-teste:
    driver: bridge 

services:
  front:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: app-flixfront
    ports:
      - 8090:8080
    restart: always
    tty: true
    volumes:
      - .:/home/app/flixtallos